# Generated by Django 5.2.17 on 2026-09-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_payment_method_payment_paymentattempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentattempt',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('succeeded', 'Thành công'), ('failed', 'Thất bại'), ('expired', 'Hết hạn'), ('cancelled', 'Đã hủy')], default='pending', max_length=16),
        ),
    ]
