# Generated by Django 5.2.17 on 2026-09-29 03:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_alter_productevent_event_type'),
        ('orders', '0003_alter_paymentattempt_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image_url', models.URLField(max_length=500)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('position', models.CharField(choices=[('home_hero', 'Hero trang chủ'), ('home_strip', 'Dải trang chủ'), ('products_top', 'Đầu trang sản phẩm')], db_index=True, max_length=24)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='engagement_banner_window_valid')],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('discount_type', models.CharField(choices=[('percent', 'Phần trăm'), ('fixed', 'Số tiền cố định')], max_length=12)),
                ('value', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_discount', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_order_value', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('per_user_limit', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='vouchers', to='catalog.category')),
                ('products', models.ManyToManyField(blank=True, related_name='vouchers', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Đang giữ'), ('redeemed', 'Đã dùng'), ('released', 'Đã hoàn')], max_length=12)),
                ('discount_amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_usage', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_usages', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='engagement.voucher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_allocation', to='orders.orderitem')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='engagement.voucherusage')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], db_index=True, default='pending', max_length=12)),
                ('moderation_note', models.CharField(blank=True, max_length=500)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['product', 'status', '-created_at'], name='engagement__product_9e85a9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='engagement_review_rating_1_5')],
            },
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='engagement_voucher_value_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('min_order_value__gte', 0)), name='engagement_voucher_min_order_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='engagement_voucher_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='voucherusage',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='engagement_usage_discount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='voucherallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='engagement_allocation_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='engagement_wishlist_user_product_uniq'),
        ),
    ]
