# Generated by Django 5.2.17 on 2026-09-14 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_business_role_groups(apps, schema_editor):
    group_model = apps.get_model("auth", "Group")
    user_model = apps.get_model("accounts", "User")
    groups = {
        name: group_model.objects.get_or_create(name=name)[0]
        for name in ("CUSTOMER", "STAFF", "ADMIN")
    }
    customer_group = groups["CUSTOMER"]
    for user in user_model.objects.filter(is_staff=False, is_superuser=False).iterator():
        customer_group.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_default', '-updated_at', 'id'),
                'indexes': [models.Index(fields=['user', '-updated_at'], name='accounts_address_user_updated')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='accounts_address_one_default_per_user')],
            },
        ),
        migrations.RunPython(create_business_role_groups, migrations.RunPython.noop),
    ]
