# Generated by Django 5.2.17 on 2026-09-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productevent',
            name='event_type',
            field=models.CharField(choices=[('view', 'Xem sản phẩm'), ('add_cart', 'Thêm giỏ hàng'), ('recommendation_impression', 'Hiển thị gợi ý'), ('recommendation_click', 'Nhấp gợi ý')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('receipt', 'Nhập kho'), ('adjustment', 'Điều chỉnh'), ('sale', 'Bán hàng'), ('cancellation', 'Hoàn do hủy đơn')], max_length=20),
        ),
    ]
