# Generated by Django 5.2.17 on 2026-09-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productevent_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('receipt', 'Nhập kho'), ('adjustment', 'Điều chỉnh'), ('sale', 'Bán hàng'), ('cancellation', 'Hoàn do hủy đơn'), ('reservation', 'Giữ hàng thanh toán online'), ('reservation_release', 'Hoàn giữ hàng hết hạn/hủy')], max_length=20),
        ),
    ]
