# Generated by Django 5.2.17 on 2026-09-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productimage_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productevent',
            name='event_type',
            field=models.CharField(choices=[('view', 'Xem sản phẩm'), ('add_cart', 'Thêm giỏ hàng'), ('recommendation_impression', 'Hiển thị gợi ý'), ('recommendation_click', 'Nhấp gợi ý'), ('wishlist_add', 'Thêm yêu thích'), ('wishlist_remove', 'Bỏ yêu thích')], db_index=True, max_length=40),
        ),
    ]
