# Generated by Django 5.2.17 on 2026-09-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('receipt', 'Nhập kho'), ('adjustment', 'Điều chỉnh'), ('sale', 'Bán hàng'), ('cancellation', 'Hoàn do hủy đơn'), ('reservation', 'Giữ hàng thanh toán online'), ('reservation_release', 'Hoàn giữ hàng hết hạn/hủy'), ('exchange_reservation', 'Giữ hàng đổi'), ('exchange_release', 'Hoàn giữ hàng đổi'), ('exchange_return', 'Nhập lại hàng đổi')], max_length=20),
        ),
    ]
