# Generated by Django 5.2.17 on 2026-09-30 04:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_stockmovement_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strategy', models.CharField(choices=[('popular', 'Phổ biến'), ('similar', 'Tương tự'), ('personalized', 'Cá nhân hóa')], db_index=True, max_length=20)),
                ('anonymous_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='catalog_variant_options_uniq',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('footwear', 'Giày dép'), ('accessory', 'Phụ kiện'), ('care', 'Chăm sóc giày')], db_index=True, default='footwear', max_length=16),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='option_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='productevent',
            name='event_type',
            field=models.CharField(choices=[('view', 'Xem sản phẩm'), ('add_cart', 'Thêm giỏ hàng'), ('recommendation_impression', 'Hiển thị gợi ý'), ('recommendation_click', 'Nhấp gợi ý'), ('wishlist_add', 'Thêm yêu thích'), ('wishlist_remove', 'Bỏ yêu thích'), ('purchase', 'Mua hàng hoàn tất')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.color'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.size'),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendation_items', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='recommendationrequest',
            name='source_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar_recommendation_requests', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='recommendationrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.recommendationrequest'),
        ),
        migrations.AddConstraint(
            model_name='recommendationitem',
            constraint=models.UniqueConstraint(fields=('request', 'product'), name='catalog_recommendation_product_uniq'),
        ),
        migrations.AddConstraint(
            model_name='recommendationitem',
            constraint=models.UniqueConstraint(fields=('request', 'rank'), name='catalog_recommendation_rank_uniq'),
        ),
    ]
