# Generated by Django 5.2.17 on 2026-09-29 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_alter_stockmovement_kind'),
        ('orders', '0003_alter_paymentattempt_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('received', 'Đã nhận hàng'), ('inspected', 'Đã kiểm hàng'), ('replacement_ready', 'Sẵn sàng giao đổi'), ('completed', 'Hoàn tất'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], db_index=True, default='pending', max_length=24)),
                ('reason', models.CharField(max_length=500)),
                ('evidence_url', models.URLField(blank=True, max_length=500)),
                ('customer_note', models.TextField(blank=True, max_length=1000)),
                ('staff_note', models.TextField(blank=True, max_length=1000)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('reservation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exchanges', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_requests', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('accepted_quantity', models.PositiveIntegerField(default=0)),
                ('disposition', models.CharField(choices=[('pending', 'Chưa kiểm'), ('restock', 'Có thể bán lại'), ('damaged', 'Hàng lỗi')], default='pending', max_length=16)),
                ('inspection_note', models.CharField(blank=True, max_length=500)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_items', to='orders.orderitem')),
                ('target_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_targets', to='catalog.productvariant')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='exchanges.exchangerequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Đang giữ'), ('captured', 'Đã xuất đổi'), ('released', 'Đã hoàn giữ')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='exchanges.exchangeitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_reservations', to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('received', 'Đã nhận hàng'), ('inspected', 'Đã kiểm hàng'), ('replacement_ready', 'Sẵn sàng giao đổi'), ('completed', 'Hoàn tất'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], max_length=24)),
                ('to_status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('received', 'Đã nhận hàng'), ('inspected', 'Đã kiểm hàng'), ('replacement_ready', 'Sẵn sàng giao đổi'), ('completed', 'Hoàn tất'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], max_length=24)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_status_changes', to=settings.AUTH_USER_MODEL)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='exchanges.exchangerequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='exchangerequest',
            index=models.Index(fields=['status', '-created_at'], name='exchanges_e_status_4eca5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='exchangerequest',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='exchanges_user_idempotency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='exchangeitem',
            constraint=models.UniqueConstraint(fields=('exchange', 'order_item'), name='exchanges_request_order_item_uniq'),
        ),
        migrations.AddConstraint(
            model_name='exchangeitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='exchanges_item_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='exchangeitem',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__lte', models.F('quantity'))), name='exchanges_received_lte_qty'),
        ),
        migrations.AddConstraint(
            model_name='exchangeitem',
            constraint=models.CheckConstraint(condition=models.Q(('accepted_quantity__lte', models.F('received_quantity'))), name='exchanges_accepted_lte_received'),
        ),
        migrations.AddConstraint(
            model_name='exchangereservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='exchanges_reservation_qty_gt_0'),
        ),
    ]
